name: Docker Compose Actions Workflow
on:
  push:
    branches: [ "bug_cli" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the stack
        run: docker-compose up -d
        
  test:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - name: Test Frontend
        uses: wei/curl@master
        with:
          args: curl http://localhost:4200
          
